## Why Littalics in wondeRland?

I've always been an autodidact. In my [+25 years of professional experience](https://www.littalics.com/littal-shemer-haim/), I was an eternal student in many fields: data science, business, technology, consultancy, writing, photography, and more. However, nothing prepared me for the wonder of learning and mastering R. 

I took my first steps into R programming in 2015 and never quit. I used R to explore various research and methodologies and leveraged it in my consultancy in many creative ways. At this point in my journey, I needed to organize my resources and experiences in R to be more productive, in the projects and workshops I offer. 

Inspired by the famous book [Alice's Adventure in Wonderland](https://en.wikipedia.org/wiki/Alice%27s_Adventures_in_Wonderland), I gathered many pieces of knowledge that comprise my story and shared them in an open-book format. Alice figured out in the book that "It's no use going back to yesterday" because she was a different person back then. However, connecting yesterday's dots brought me to the person I am today, professionally and personally. Returning to my archive was a way to combine my learning dots into solid content that represents me today.

The nickname Littalics is another representation of my connected dots. It started as Littalics on [Twitter](https://twitter.com/Littalics) and [Facebook](https://www.facebook.com/Littalics). This nickname referred to Analytics, Statistics, Infographics, Ethics, and all other hashtags ended with the suffix 'ics.' Eventually, people recognized me off-line with that name. So, [Littalics](https://www.littalics.com/) became a domain name and a business identity.

The title of this book, Littalics in wondeRland, implies that it is about my journey in the field and my attempt to organize and share the complex body of knowledge that serves me. But before we take the deep dive into R, I'd like to share some context on the domain of expertise in which I used R. 
