# People Analytics Methods and Use Cases


I met many HR Leaders and People Analysts over the years, all eager to make an impact in their roles. However, I couldn't skip noticing how our perspectives differ regarding how you start making an impact.

My perspective comes from data science, in which studies aim to discover patterns in data and derive meaningful information to support business decisions. People Analytics, defined as the data science of HR, is all about exploring, inferring, and communicating data patterns to support decisions related to people.

To support decisions, always start your analysis with a question in mind. Such a question, handled with the proper analytics process, should lead to actionable insights. If you begin your analytics initiative with data analysis and not a question in mind, there is always a high chance of finding exciting results. However, your results will not affect the business aside from losing valuable managerial attention.

A question could be a key concern, a goal, or a challenge for the business. In the case of a People Analytics project, you hypothesize how human performance or behavior impacts that key concern, goal, or challenge. Then you define what you need to measure to test that hypothesis. Having the hypothesis and the measures to test it makes you ready to source the data and start the analytics process.

The data in your organization shed light on the business's current situation and enable an understanding of its factors, directing your intervention and guaranteeing that you discuss your insights in a broader context of the business and workforce markets. However, many HR professionals start elsewhere - with programs, being confident about the organizational development point of view. Even when data is their starting point, it often takes the form of reporting and not exploring.

What is the difference between reporting and exploring? To explore data, you must have an analytical mindset. It enables you to analyze information and identify patterns in the data to solve problems. In other words, you use your curiosity by asking the question, "why?".

Dashboards and other reporting methods present different metrics and KPIs and answer the questions: Did we reach our goals? How far are we from achieving our goals? However, by using dashboards, we can't answer the question, "why?". So instead, we need to analyze the factors driving those KPIs on our dashboards.

I don't expect HR professionals to become data scientists and run advanced statistics to identify patterns in the data that reveal the factors of KPIs. Still, I'm sure that being a better inner client of data professionals and solutions is essential, and a key to their success is asking, "why?". It will enable them to tell a straightforward story, impact any topic related to people, track improvement and progress, and indeed contribute and impact the business.

Therefore, in the following use cases, I'll go beyond reporting and dashboarding on the one hand, and I won't jump to recommended interventions and programs on the other hand. Instead, I will lead the discussion to focus on exploration and demonstrate an analytical mindset that leverages data science in the HR department. 

The use cases simulate a conversation with a data scientist that supports HR work. Their descriptions include the question in mind, data sources, HR briefing, analytics methods review, analysis using R, storytelling with data, and conclusions. I encourage you to generalize the use cases in real-life situations.
